### ISSUE TITLE
Error in running the application

### ISSUE THREAD

**Issue by RamEswar78** [SanthiKumarYadavalli/bros#9]
Today ,when I was very keen to know about the brthday of a person, with that energy and enthusiaism I opened maha-thanos but it showing "oh no unable to run the application"
![image](https://github.com/user-attachments/assets/ef145690-04b3-4c4f-ba2f-06e1be3130e3)

**Comment by SanthiKumarYadavalli** [comment]
Sorry for the inconvenience. It happens sometimes due to a problem with Streamlit Cloud which we don't know why.
Fortunately, The error message vanishes after a quick reboot of the app.
Now, maha-thanos is brought back to life.

Always be energetic and enthusiastic !
